spring:
  profiles:
    active: dev
  application:
    name: user

  main:
    allow-circular-references: false

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    entity-packages-to-scan: com.distributedx.user
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        column_ordering_strategy: legacy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties.hibernate.format_sql: false